package com.grandmagic.readingmate.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.grandmagic.readingmate.bean.db.BookComment;
import com.grandmagic.readingmate.bean.db.Contacts;
import com.grandmagic.readingmate.bean.db.InviteMessage;
import com.grandmagic.readingmate.bean.db.ChatDraftBox;

import com.grandmagic.readingmate.db.BookCommentDao;
import com.grandmagic.readingmate.db.ContactsDao;
import com.grandmagic.readingmate.db.InviteMessageDao;
import com.grandmagic.readingmate.db.ChatDraftBoxDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookCommentDaoConfig;
    private final DaoConfig contactsDaoConfig;
    private final DaoConfig inviteMessageDaoConfig;
    private final DaoConfig chatDraftBoxDaoConfig;

    private final BookCommentDao bookCommentDao;
    private final ContactsDao contactsDao;
    private final InviteMessageDao inviteMessageDao;
    private final ChatDraftBoxDao chatDraftBoxDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookCommentDaoConfig = daoConfigMap.get(BookCommentDao.class).clone();
        bookCommentDaoConfig.initIdentityScope(type);

        contactsDaoConfig = daoConfigMap.get(ContactsDao.class).clone();
        contactsDaoConfig.initIdentityScope(type);

        inviteMessageDaoConfig = daoConfigMap.get(InviteMessageDao.class).clone();
        inviteMessageDaoConfig.initIdentityScope(type);

        chatDraftBoxDaoConfig = daoConfigMap.get(ChatDraftBoxDao.class).clone();
        chatDraftBoxDaoConfig.initIdentityScope(type);

        bookCommentDao = new BookCommentDao(bookCommentDaoConfig, this);
        contactsDao = new ContactsDao(contactsDaoConfig, this);
        inviteMessageDao = new InviteMessageDao(inviteMessageDaoConfig, this);
        chatDraftBoxDao = new ChatDraftBoxDao(chatDraftBoxDaoConfig, this);

        registerDao(BookComment.class, bookCommentDao);
        registerDao(Contacts.class, contactsDao);
        registerDao(InviteMessage.class, inviteMessageDao);
        registerDao(ChatDraftBox.class, chatDraftBoxDao);
    }
    
    public void clear() {
        bookCommentDaoConfig.clearIdentityScope();
        contactsDaoConfig.clearIdentityScope();
        inviteMessageDaoConfig.clearIdentityScope();
        chatDraftBoxDaoConfig.clearIdentityScope();
    }

    public BookCommentDao getBookCommentDao() {
        return bookCommentDao;
    }

    public ContactsDao getContactsDao() {
        return contactsDao;
    }

    public InviteMessageDao getInviteMessageDao() {
        return inviteMessageDao;
    }

    public ChatDraftBoxDao getChatDraftBoxDao() {
        return chatDraftBoxDao;
    }

}
