package com.grandmagic.readingmate.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.grandmagic.readingmate.bean.response.Contacts;
import com.grandmagic.readingmate.bean.response.InviteMessage;

import com.grandmagic.readingmate.db.ContactsDao;
import com.grandmagic.readingmate.db.InviteMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsDaoConfig;
    private final DaoConfig inviteMessageDaoConfig;

    private final ContactsDao contactsDao;
    private final InviteMessageDao inviteMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsDaoConfig = daoConfigMap.get(ContactsDao.class).clone();
        contactsDaoConfig.initIdentityScope(type);

        inviteMessageDaoConfig = daoConfigMap.get(InviteMessageDao.class).clone();
        inviteMessageDaoConfig.initIdentityScope(type);

        contactsDao = new ContactsDao(contactsDaoConfig, this);
        inviteMessageDao = new InviteMessageDao(inviteMessageDaoConfig, this);

        registerDao(Contacts.class, contactsDao);
        registerDao(InviteMessage.class, inviteMessageDao);
    }
    
    public void clear() {
        contactsDaoConfig.clearIdentityScope();
        inviteMessageDaoConfig.clearIdentityScope();
    }

    public ContactsDao getContactsDao() {
        return contactsDao;
    }

    public InviteMessageDao getInviteMessageDao() {
        return inviteMessageDao;
    }

}
